//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class MotorDataMsg : Message
    {
        public const string k_RosMessageName = "dynamixel_sdk_custom_interfaces/SetPosition";
        public override string RosMessageName => k_RosMessageName;

        public int id;
        public Int32 position;


        public MotorDataMsg()
        {
            this.id = 1;
            this.position = 0;

        }

        public MotorDataMsg(int id, Int32 position)
        {
            this.id = id;
            this.position = position;

        }

        public static MotorDataMsg Deserialize(MessageDeserializer deserializer) => new MotorDataMsg(deserializer);

        private MotorDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.position);

        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.position);

        }

        public override string ToString()
        {
            return "SetPositionMsg: " +
            "\nid: " + id.ToString() +
            "\nposition: " + position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
