//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class GetPositionResponse : Message
    {
        public const string k_RosMessageName = "dynamixel_sdk_custom_interfaces/GetPosition";
        public override string RosMessageName => k_RosMessageName;

        public MotorDataMsg output;

        public GetPositionResponse()
        {
            this.output = new MotorDataMsg();
        }

        public GetPositionResponse(MotorDataMsg output)
        {
            this.output = output;
        }

        public static GetPositionResponse Deserialize(MessageDeserializer deserializer) => new GetPositionResponse(deserializer);

        private GetPositionResponse(MessageDeserializer deserializer)
        {
            this.output = MotorDataMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.output);
        }

        public override string ToString()
        {
            return "GetPositionResponse: " +
            "\noutput: " + output.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
